baseURL = "https://kyb3rcipher.com"
title = "Kyb3r Cipher"

# language
languageCode = "en"
defaultContentLanguage = "en"

# theme
theme = "DoIt"
# emojis enable
enableEmoji = true
# git info update in posts
enableGitInfo = true
enableRobotsTXT = true
[params.page]
# font awesome enable
fontawesome = true
# pages styles ("normal", "wide")
pageStyle = "normal"

[params]
  # DoIt theme version
  version = "0.2.X"
  # site description
  description = "Kyb3r Cipher Blog and Website"
  # site keywords
  keywords = ["Kyb3r Cipher", "Cipher Kyb3r", "kyb3rcipher", "@kyb3rcipher", "Kyb3r Cipher Blog", "Cipher",]
  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"
  # others
  enablePWA = true
  dateFormat = "2006-01-02"
  gitRepo = "https://github.com/kyb3rcipher/kyb3rcipher.com"
  # website images for Open Graph and Twitter Cards
  images = ["/logo.png"]

[params.app]
  # optional site title override for the app when added to an iOS home screen or Android launcher
  title = "Kyb3r Cipher"
  # whether to omit favicon resource links
  noFavicon = false
  # modern SVG favicon to use in place of older style .png and .ico files
  svgFavicon = ""
  # Android browser theme color
  themeColor = "#ffffff"
  # Safari mask icon color
  iconColor = "#5bbad5"
  # Windows v8-10 tile color
  tileColor = "#da532c"

  # Home page config
  [params.home]
    # amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      # Gravatar Profile Photo Email
      gravatarEmail = "me@kyb3rcipher.com"
      title = "Kyb3r Cipher"
      subtitle = "💻 Geek/Programmer/SysAdmin/Hacker? • 📣 he/him"
      typeit = true
      social = true
    # Home page posts
    [params.home.posts]
      enable = true
      # posts in home
      paginate = 6
      defaultHiddenFromHomePage = false

[params.social]
  GitHub    = "kyb3rcipher"
  Twitter   = "kyb3rcipher"
  Instagram = "kyb3rcipher"
  Telegram  = "kyb3rcipher"
  Linkedin  = "kyb3rcipher"
  PGP       = "/kyb3rcipher.asc"
  Personal  = "https://itsgaelgt.ga"
  Email     = "me@kyb3rcipher.com"
  RSS       = false

# Navbar config
[menu]
  [[ menu.main ]]
    identifier = "blog"
    name = "Blog"
    pre = '<i class="fas fa-newspaper"></i>'
    title = "My blog."
    url = "/posts"
    weight = 1

  [[ menu.main ]]
    identifier = "profiles"
    name = "Profiles"
    pre = '<i class="fas fa-users"></i>'
    title = "My all official accounts."
    url = "/profiles"
    weight = 2

  [[ menu.main ]]
    identifier = "proyects"
    name = "Proyects"
    pre = '<i class="fas fa-code"></i>'
    title = "My proyects."
    url = "/proyects"
    weight = 3

  [[ menu.main ]]
    identifier = "about"
    name = "About"
    pre = '<i class="fas fa-info"></i>'
    title = "About and contact me."
    url = "/about"
    weight = 4 

# Header config
[params.header]
  # desktop header mode ("fixed", "normal", "auto")
  desktopMode = "fixed"
  # mobile header mode ("fixed", "normal", "auto")
  mobileMode = "auto"
  [params.header.title]
    name = "Kyb3r :]"
    typeit = "true"
  # typing
  [params.typeit]
    speed = 100
    cursorSpeed = 1000
    cursorChar = "|"
    duration = -1

# Footer config
[params.footer]
  enable = true
  # Gohugo info
  hugo = false
  # copyright infomation
  copyright = true
  # author information
  author = true
  # site creation time
  since = 2021
  license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">License & Copyright</a>'

# section (all posts) page config
[params.section]
  # special amount of posts in each section page
  paginate = 20
  # date format (month and day)
  dateFormat = "01-02"
  # amount of RSS pages
  rss = 10

# page config
[params.list]
  # special amount of posts in each list page
  paginate = 20
  # date format (month and day)
  dateFormat = "01-02"
  # amount of RSS pages
  rss = 10

[params.page.share]
  enable = true
  Reddit = true
  Twitter = true
  Facebook = true
  Whatsapp = true
  HackerNews = true

# Cookies consent config
[params.cookieconsent]
  enable = true
  [params.cookieconsent.content]
    message = "This website uses cookies and analytics to improve your user experience we respect your privacy."

[params.page.toc] # To apply the pageStyle when compiling into vercel/netlify
    # whether to enable the table of the contents
    enable = true
    # whether to keep the static table of the contents in front of the post
    keepStatic = false
    # whether to make the table of the contents in the sidebar automatically collapsed
    auto = true

# Analytics config
[params.analytics]
  enable = true
  # Google Analytics
  [params.analytics.google]
    id = "G-Z9NMTNQE53"
    # whether to anonymize IP
    anonymizeIP = true

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe= true
