baseURL = "https://kyb3rvizsla.com"
title = "Kyb3r Vizsla"

# language
languageCode = "en"
defaultContentLanguage = "en"

# theme
theme = "DoIt"
# emojis enable
enableEmoji = true
# git info update in posts
enableGitInfo = true
enableRobotsTXT = true
[params.page]
# font awesome enable
fontawesome = true
# pages styles ("normal", "wide")
pageStyle = "wide"

[params]
  # DoIt theme version
  version = "0.2.X"
  # site description
  description = "Kyb3r Vizsla Blog and Website"
  # site keywords
  keywords = ["Kyb3r", "Kyb3r Vizsla", "Hacker", "Geek", "Gael", "Gael Vizsla", "Aesthetic",]
  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"
  # others
  enablePWA = true
  dateFormat = "2006-01-02"
  gitRepo = "https://github.com/kyb3rvizsla/kyb3rvizsla.com"
  # website images for Open Graph and Twitter Cards
  images = ["/logo.png"]

[params.app]
  # optional site title override for the app when added to an iOS home screen or Android launcher
  title = "Kyb3r Vizsla"
  # whether to omit favicon resource links
  noFavicon = false
  # modern SVG favicon to use in place of older style .png and .ico files
  svgFavicon = ""
  # Android browser theme color
  themeColor = "#ffffff"
  # Safari mask icon color
  iconColor = "#5bbad5"
  # Windows v8-10 tile color
  tileColor = "#da532c"

  # Home page config
  [params.home]
    # amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      # Gravatar Profile Photo Email
      gravatarEmail = "me@kyb3rvizsla.com"
      title = "Kyb3r Vizsla"
      subtitle = "💻 Programmer/SysAdmin/Hacker?"
      typeit = true
      social = true
      disclaimer = "Don't forget to check:"
    # Home page posts
    [params.home.posts]
      enable = true
      # posts in home
      paginate = 6
      defaultHiddenFromHomePage = false

[params.social]
  GitHub = "kyb3rvizsla"
  Twitter = "/profiles/twitter"
  Instagram = "/profiles/instagram"
  Linkedin = "kyb3rvizsla"
  Keybase = "kyb3rvizsla"
  Telegram = "kyb3rvizsla"
  Pronouns = "@kyb3rvizsla"
  Snapchat = "gaelvizsla"
  Email = "contact@kyb3rvizsla.com"
  RSS = true

# Navbar config
[menu]
  [[ menu.main ]]
    identifier = "blog"
    name = "Blog"
    pre = '<i class="fas fa-newspaper"></i>'
    title = "My blog."
    url = "/posts"
    weight = 1

  [[ menu.main ]]
    identifier = "profiles"
    name = "Profiles"
    pre = '<i class="fas fa-users"></i>'
    title = "My all official accounts."
    url = "/profiles"
    weight = 2

    [[ menu.main ]]
    identifier = "proyects"
    name = "Proyects"
    pre = '<i class="fas fa-puzzle-piece"></i>'
    title = "My proyects."
    url = "/proyects"
    weight = 3

  [[ menu.main ]]
    identifier = "writeups"
    name = "Writeups"
    pre = '<i class="fas fa-spider"></i>'
    title = "CTF writeups."
    url = "/categories/writeup"
    weight = 4

  [[ menu.main ]]
    identifier = "about"
    name = "About"
    pre = '<i class="fas fa-info"></i>'
    title = "About and contact me."
    url = "/about"
    weight = 5

# Header config
[params.header]
  # desktop header mode ("fixed", "normal", "auto")
  desktopMode = "fixed"
  # mobile header mode ("fixed", "normal", "auto")
  mobileMode = "auto"
  [params.header.title]
    name = "Kyb3r"
    typeit = "true"

# Footer config
[params.footer]
  enable = true
  # Gohugo info
  hugo = false
  # copyright infomation
  copyright = true
  # author information
  author = true
  # site creation time
  since = 2021
  license = '<a rel="license external nofollow noopener noreffer" href="/license">License & Copyright</a>'

# section (all posts) page config
[params.section]
  # special amount of posts in each section page
  paginate = 20
  # date format (month and day)
  dateFormat = "01-02"
  # amount of RSS pages
  rss = 10

# page config
[params.list]
  # special amount of posts in each list page
  paginate = 20
  # date format (month and day)
  dateFormat = "01-02"
  # amount of RSS pages
  rss = 10

[params.page.share]
  enable = true
  Reddit = true
  Twitter = true
  Facebook = true
  Whatsapp = true
  HackerNews = true

# Cookies consent config
[params.cookieconsent]
  enable = true
  [params.cookieconsent.content]
    message = "This website uses cookies and analytics to improve your user experience we respect your privacy."

[params.page.toc] # To apply the pageStyle when compiling into vercel/netlify
    # whether to enable the table of the contents
    enable = true
    # whether to keep the static table of the contents in front of the post
    keepStatic = false
    # whether to make the table of the contents in the sidebar automatically collapsed
    auto = true

# Analytics config
[params.analytics]
  enable = true
  # Google Analytics
  [params.analytics.google]
    id = "G-WGH7R604WZ"
    # whether to anonymize IP
    anonymizeIP = true

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe= true
